In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import KBinsDiscretizer

In [6]:
df=pd.read_csv('/kaggle/input/datasets/brendan45774/test-file/tested.csv',usecols=['Age','Fare','Survived'])

In [7]:
df.head()

   Survived   Age     Fare
0         0  34.5   7.8292
1         1  47.0   7.0000
2         0  62.0   9.6875
3         0  27.0   8.6625
4         1  22.0  12.2875

In [8]:
df.dropna(inplace=True)

In [9]:
df.shape

(331, 3)

In [10]:
X=df.iloc[:,1:]
y=df.iloc[:,0]

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
X_train.head()

       Age     Fare
281   0.75  13.7750
96   76.00  78.8500
341  32.00   7.5792
18   27.00   7.9250
26   22.00  61.9792

In [22]:
clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print("Accuracy:",accuracy_score(y_pred,y_test))
print("Accuracy using cross validation:",np.mean(cross_val_score(clf,X,y,cv=10,scoring='accuracy')))

Accuracy: 0.5970149253731343
Accuracy using cross validation: 0.5621212121212121

In [51]:
Kbin_age=KBinsDiscretizer(n_bins=15,encode='ordinal',strategy='quantile')
Kbin_fare=KBinsDiscretizer(n_bins=15,encode='ordinal',strategy='quantile')

In [52]:
trf=ColumnTransformer([
    ('first',Kbin_age,[0]),
    ('second',Kbin_fare,[1])
])

In [53]:
X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.fit_transform(X_test)

In [54]:
trf.named_transformers_

{'first': KBinsDiscretizer(encode='ordinal', n_bins=15),
 'second': KBinsDiscretizer(encode='ordinal', n_bins=15)}

In [55]:
trf.named_transformers_['first'].n_bins_

array([15])

In [56]:
trf.named_transformers_['first'].bin_edges_

array([array([ 0.17,  2.4 , 12.8 , 18.  , 21.  , 22.  , 22.7 , 24.  , 25.2 ,
              26.3 , 28.  , 31.4 , 39.  , 42.  , 48.6 , 61.  ])             ],
      dtype=object)

In [57]:
trf.named_transformers_['second'].bin_edges_

array([array([  6.4958 ,   7.42832,   7.775  ,   7.81248,   8.05   ,   9.225  ,
               10.5    ,  13.62   ,  20.22   ,  22.23   ,  27.75   ,  31.4325 ,
               50.39664,  61.     , 128.33   , 263.     ])                     ],
      dtype=object)

In [58]:
output=pd.DataFrame({
    'Age':X_train['Age'],
    'Age trf':X_train_trf[:,0],
    'Fare':X_train['Fare'],
    'Fare trf':X_train_trf[:,1]
})

In [59]:
output.head()

       Age  Age trf     Fare  Fare trf
281   0.75      0.0  13.7750       6.0
96   76.00     14.0  78.8500      13.0
341  32.00      9.0   7.5792       1.0
18   27.00      6.0   7.9250       3.0
26   22.00      4.0  61.9792      12.0

In [60]:
clf.fit(X_train_trf,y_train)
y_pred_trf=clf.predict(X_test_trf)
print("Accuracy:",accuracy_score(y_pred_trf,y_test))

Accuracy: 0.6119402985074627

In [64]:
X_trf=trf.fit_transform(X)
print("Accuracy using cross validation:",np.mean(cross_val_score(clf,X_trf,y,cv=10,scoring='accuracy')))

Accuracy using cross validation: 0.5741532976827095

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_discretization.py:306: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_discretization.py:306: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(