In [1]:
import pandas as pd

#Importing Data

In [2]:
df=pd.read_csv("/kaggle/input/datasets/divjotbedi/top-rated-10000-movies/df_movie.csv")

#How Big Data is?

In [5]:
df.shape

(10000, 8)

info about data

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    10000 non-null  int64
 1   id            10000 non-null  int64
 2   title         10000 non-null  object
 3   release_date  9997 non-null   object
 4   popularity    10000 non-null  float64
 5   vote_average  10000 non-null  float64
 6   vote_count    10000 non-null  int64
 7   overview      9998 non-null   object
dtypes: float64(2), int64(3), object(3)
memory usage: 625.1+ KB

How Data looks like?

In [9]:
df.head(10)

,Unnamed: 0,id,title,release_date,popularity,vote_average,vote_count,overview
0,0,278,The Shawshank Redemption,1994-09-23,42.1605,8.717,29992,Imprisoned in the 1940s for the double murder ...
1,1,238,The Godfather,1972-03-14,36.5278,8.687,22658,"Spanning the years 1945 to 1955, a chronicle o..."
2,2,240,The Godfather Part II,1974-12-20,25.5386,8.572,13720,In the continuing saga of the Corleone crime f...
3,3,424,Schindler's List,1993-12-15,23.5837,8.567,17246,The true story of how businessman Oskar Schind...
4,4,389,12 Angry Men,1957-04-10,19.3006,8.556,9844,The defense and the prosecution have rested an...
5,5,1181678,¿Quieres ser mi hijo?,2023-09-21,7.9646,8.546,305,"Lu, a conformist woman in her forties, learns ..."
6,6,129,Spirited Away,2001-07-20,28.6520,8.533,18105,"A young girl, Chihiro, becomes trapped in a st..."
7,7,155,The Dark Knight,2008-07-16,41.0006,8.527,35387,Batman raises the stakes in his war on crime. ...
8,8,19404,Dilwale Dulhania Le Jayenge,1995-10-20,11.6598,8.516,4567,"Raj is a rich, carefree, happy-go-lucky second..."
9,9,497,The Green Mile,1999-12-10,26.0735,8.505,18994,A supernatural tale set on death row in a Sout...

#NULL values count

In [12]:
df.isnull().sum()

Unnamed: 0      0
id              0
title           0
release_date    3
popularity      0
vote_average    0
vote_count      0
overview        2
dtype: int64

#how data looks mathematically?

In [13]:
df.describe()

        Unnamed: 0            id    popularity  vote_average    vote_count
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000
mean    4999.50000  2.270300e+05      4.460590      6.736070   2091.774400
std     2886.89568  3.021682e+05      9.142035      0.654126   3342.697826
min        0.00000  2.000000e+00      0.005800      5.471000    300.000000
25%     2499.75000  1.035250e+04      2.029100      6.203750    476.000000
50%     4999.50000  4.162000e+04      2.934800      6.700000    868.000000
75%     7499.25000  4.064295e+05      4.669550      7.200000   2096.000000
max     9999.00000  1.472638e+06    304.572000      8.717000  39214.000000

#Duplicated items

In [14]:
df.duplicated().sum()

np.int64(0)

#correlation

<bound method DataFrame.corr of       Unnamed: 0       id                     title release_date  popularity  \
0              0      278  The Shawshank Redemption   1994-09-23     42.1605
1              1      238             The Godfather   1972-03-14     36.5278
2              2      240     The Godfather Part II   1974-12-20     25.5386
3              3      424          Schindler's List   1993-12-15     23.5837
4              4      389              12 Angry Men   1957-04-10     19.3006
...          ...      ...                       ...          ...         ...
9995        9995     9796                  Turistas   2006-12-01      2.7055
9996        9996   253310                 Premature   2014-07-02      2.7309
9997        9997    87368                  17 Girls   2011-06-13      0.5833
9998        9998  1063422                The Strays   2023-02-17      2.0145
9999        9999    75198            Welcome Aboard   2011-10-05      1.2395

      vote_average  vote_count  \
0            8.717       29992
1            8.687       22658
2            8.572       13720
3            8.567       17246
4            8.556        9844
...            ...         ...
9995         5.471         879
9996         5.473         478
9997         5.500         327
9998         5.500         399
9999         5.500         540

                                               overview
0     Imprisoned in the 1940s for the double murder ...
1     Spanning the years 1945 to 1955, a chronicle o...
2     In the continuing saga of the Corleone crime f...
3     The true story of how businessman Oskar Schind...
4     The defense and the prosecution have rested an...
...                                                 ...
9995  A group of young backpackers' vacation turns s...
9996  On the most important day of his young life, a...
9997  When Camille accidentally becomes pregnant, sh...
9998  A Black woman's meticulously crafted life of p...
9999  Isabelle, HR of a large cruise company, made t...

[10000 rows x 8 columns]>